In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup

import time
import random as rd
import pandas as pd

import re

import warnings
warnings.filterwarnings('ignore')

In [4]:
Path_driver='D:\Logiciels\Driver_selenium\chromedriver_win32_V108\chromedriver.exe' #chromedriver.exe
options = webdriver.ChromeOptions()
#options.add_argument('-headless') #hide the chrome page

# Ecoles d'ingénieurs

In [131]:
def Classement_Ingenieurs():
    df = pd.DataFrame(columns = ['Ecole', 'Rank', 'Statut','Duree','Alternance','Note'])
    rank=1
    
    for page in range(1,10):#9 pages de classement
        url = 'https://www.letudiant.fr/classements/classement-des-ecoles-d-ingenieurs.html?page='+str(page)
        driver = webdriver.Chrome(Path_driver, options=options)

        time.sleep(int(rd.randint(1,2)))   
        driver.get(url)

        time.sleep(int(rd.randint(1,2)))   
        soup=BeautifulSoup(driver.page_source,'html.parser') #html data of the page

        regex = re.compile('^laureate-row-')#laureate-row-1, laureate-row-2,...
        data=soup.find_all('tr', {"id" : regex})#toutes les fiches écoles
        data_notes=soup.find_all('tr', {"data-toggle-target" : regex})#évaluations des écoles
        driver.close()    
        
        for ecole in range(len(data)):
            nom=data[ecole].a.get('data-layer-event-lab')
            
            L=data[ecole].ul.find_all('li')
            statut=L[0].text.strip().split(':')[-1].strip() #Statut : Public => Public
            duree=L[1].text.strip().split(':')[-1].split(' ')[1] #Durée du cursus : 3 ans => 3
            alternance=L[2].text.strip().split(':')[-1].strip() #Alternance : Non => Non
            
            note=data_notes[ecole].find_all('td')[-1].text.strip()
            
            df = df.append({'Ecole':nom, 'Rank':rank,'Statut':statut,'Duree':duree, 'Alternance':alternance, 'Note':note},ignore_index=True)
            rank+=1
            
    df.to_csv('Classement_ingenieurs.csv',';',mode='w',index=False,header=True,encoding='utf-8')

In [132]:
Classement_Ingenieurs()

In [193]:
df=pd.read_csv('Classement_ingenieurs.csv',sep=';')
df.head(10)

,Ecole,Rank,Statut,Duree,Alternance,Note
0,École Polytechnique - Palaiseau,1,Public,3,Non,55/58
1,Télécom Paris,2,Public,3,Non,54/58
2,CentraleSupélec,3,Public,3,Oui,52/58
3,École des ponts ParisTech - Marne-la-vallée,4,Public,3,Non,51/58
4,École des mines ParisTech,5,Public,3,Oui,50/58
5,IMT Atlantique,6,Public,3,Oui,50/58
6,ENSTA Paris,7,Public,3,Oui,49/58
7,École des mines - Nancy,8,Public,3,Oui,47/58
8,École centrale - Lille,9,Public,3,Oui,46/58
9,INSA Lyon,10,Public,5,Oui,46/58

# Ecoles de commerces

In [147]:
def Classement_commerces():
    df = pd.DataFrame(columns = ['Ecole', 'Rank', 'Type','Note'])
    rank=1
    
    for page in range(1,10):#9 pages de classement
        url = 'https://www.letudiant.fr/classements/classement-des-grandes-ecoles-de-commerce.html?page='+str(page)
        driver = webdriver.Chrome(Path_driver, options=options)

        time.sleep(int(rd.randint(1,2)))   
        driver.get(url)

        time.sleep(int(rd.randint(1,2)))   
        soup=BeautifulSoup(driver.page_source,'html.parser') #html data of the page

        regex = re.compile('^laureate-row-')#laureate-row-1, laureate-row-2,...
        data=soup.find_all('tr', {"id" : regex})#toutes les fiches écoles
        data_notes=soup.find_all('tr', {"data-toggle-target" : regex})#évaluations des écoles
        driver.close()    
        
        for ecole in range(len(data)):
            nom=data[ecole].a.get('data-layer-event-lab')
            
            L=data[ecole].ul.find_all('li')
            type_ecole=L[0].text.strip().split(':')[-1].strip() #Statut : Public => Public
            
            note=data_notes[ecole].find_all('td')[-1].text.strip()
            
            df = df.append({'Ecole':nom, 'Rank':rank,'Type':statut,'Note':note},ignore_index=True)
            rank+=1
            
    df.to_csv('Classement_commerces.csv',';',mode='w',index=False,header=True,encoding='utf-8')

In [148]:
Classement_commerces()

In [ ]:
df=pd.read_csv('Classement_commerces.csv',sep=';')
df.head(10)